## You have been hired by a rookie movie producer to help him decide what type of movies to produce and which actors to cast. You have to back your recommendations based on thorough analysis of the data he shared with you which has the list of 3000 movies and the corresponding details.

## As a data scientist, you have to first explore the data and check its sanity.

## Further, you have to answer the following questions:
1. ### <b> Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.</b>
2. ### <b>This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)? </b>
3. ### <b> Find out the unique genres of movies in this dataset.</b>
4. ### <b> Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI? </b>
5. ### <b> Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor. </b>
6. ### <b>Top 3 directors prefer which actors the most? </b>

# Importing libraries and data set

In [1]:
#Importing package
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
imdb_df = pd.read_csv('imdb_data_set.csv')

# Exploring data

In [3]:
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [4]:
imdb_df.shape

(3000, 23)

In [5]:
imdb_df.head(3)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000

In [6]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [7]:
crew_list = imdb_df[imdb_df['crew'].notnull()].crew
crew_list

0       [{'credit_id': '59ac067c92514107af02c8c8', 'de...
1       [{'credit_id': '52fe43fe9251416c7502563d', 'de...
2       [{'credit_id': '54d5356ec3a3683ba0000039', 'de...
3       [{'credit_id': '52fe48779251416c9108d6eb', 'de...
4       [{'credit_id': '52fe464b9251416c75073b43', 'de...
                              ...
2995    [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...
2996    [{'credit_id': '5716b72ac3a3686678012c84', 'de...
2997    [{'credit_id': '52fe443a9251416c7502d579', 'de...
2998    [{'credit_id': '556f817b9251410866000a63', 'de...
2999    [{'credit_id': '5391990d0e0a260fb5001629', 'de...
Name: crew, Length: 2984, dtype: object

In [8]:
c=imdb_df[imdb_df.crew.isna()].original_title
c

470     The Book of Mormon Movie, Volume 1: The Journey
518                                        Wonder Woman
680                              The Day After Tomorrow
906                               The Dark Knight Rises
934                                John Wick: Chapter 2
1303                       Mr. Smith Goes to Washington
1617                 The Assassination of Richard Nixon
1783                                              Logan
2014                            The Wolf of Wall Street
2302                                      Happy Weekend
2384                                         Yolngu Boy
2448                                         15 Minutes
2518                      You Don't Mess with the Zohan
2623        Valerian and the City of a Thousand Planets
2883                     The X Files: I Want to Believe
2965                                     Les Misérables
Name: original_title, dtype: object

In [9]:
len(crew_list)

2984

In [10]:
imdb_df['crew'][1]

"[{'credit_id': '52fe43fe9251416c7502563d', 'department': 'Directing', 'gender': 2, 'id': 1201, 'job': 'Director', 'name': 'Garry Marshall', 'profile_path': '/kx77E8p5rnEmKxIhFT0qWCEMEik.jpg'}, {'credit_id': '52fe43fe9251416c75025667', 'department': 'Camera', 'gender': 2, 'id': 1214, 'job': 'Director of Photography', 'name': 'Charles Minsky', 'profile_path': None}, {'credit_id': '52fe43fe9251416c75025661', 'department': 'Sound', 'gender': 2, 'id': 4500, 'job': 'Original Music Composer', 'name': 'John Debney', 'profile_path': '/hTrlvZlDXQk49nfc2BM9sjKfJv.jpg'}, {'credit_id': '52fe43fe9251416c7502564f', 'department': 'Production', 'gender': 1, 'id': 8851, 'job': 'Producer', 'name': 'Whitney Houston', 'profile_path': '/69ouDnXnmklYPr4sMJXWKYz81AL.jpg'}, {'credit_id': '52fe43fe9251416c7502566d', 'department': 'Editing', 'gender': 0, 'id': 12970, 'job': 'Editor', 'name': 'Bruce Green', 'profile_path': '/yplxWPVgwK1b33AjvbhM9mWX2Aw.jpg'}, {'credit_id': '52fe43fe9251416c75025655', 'department': 'Production', 'gender': 2, 'id': 38415, 'job': 'Producer', 'name': 'Mario Iscovich', 'profile_path': None}, {'credit_id': '52fe43fe9251416c7502565b', 'department': 'Production', 'gender': 1, 'id': 38416, 'job': 'Executive Producer', 'name': 'Ellen H. Schwartz', 'profile_path': '/6WInjABr1sAYGXaa5qOvSrsHIqP.jpg'}, {'credit_id': '52fe43fe9251416c75025649', 'department': 'Production', 'gender': 1, 'id': 59973, 'job': 'Producer', 'name': 'Debra Martin Chase', 'profile_path': None}, {'credit_id': '52fe43fe9251416c75025643', 'department': 'Writing', 'gender': 1, 'id': 25539, 'job': 'Screenplay', 'name': 'Shonda Rhimes', 'profile_path': '/4c77e347InbTAlw9lGvORpZBHV6.jpg'}]"

In [11]:
imdb_df[imdb_df['genres'].notnull()].genres

0                          [{'id': 35, 'name': 'Comedy'}]
1       [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2                           [{'id': 18, 'name': 'Drama'}]
3       [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...
4       [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
                              ...
2995    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2996    [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...
2997    [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999    [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...
Name: genres, Length: 2993, dtype: object

In [12]:
imdb_df[imdb_df['genres'].notnull()].budget

0       14000000
1       40000000
2        3300000
3        1200000
4              0
          ...
2995           0
2996           0
2997    65000000
2998    42000000
2999    35000000
Name: budget, Length: 2993, dtype: int64

In [13]:
imdb_df['genres'][0]

"[{'id': 35, 'name': 'Comedy'}]"

In [14]:
imdb_df['genres'][1]

"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 10749, 'name': 'Romance'}]"

* Keeping only important columns

In [15]:
column_to_keep = ['budget','genres','imdb_id','original_language','original_title','revenue','cast','crew']

In [16]:
df = imdb_df[column_to_keep]

In [17]:
df.columns

Index(['budget', 'genres', 'imdb_id', 'original_language', 'original_title',
       'revenue', 'cast', 'crew'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             3000 non-null   int64
 1   genres             2993 non-null   object
 2   imdb_id            3000 non-null   object
 3   original_language  3000 non-null   object
 4   original_title     3000 non-null   object
 5   revenue            3000 non-null   int64
 6   cast               2987 non-null   object
 7   crew               2984 non-null   object
dtypes: int64(2), object(6)
memory usage: 187.6+ KB

In [19]:
df.shape

(3000, 8)

In [20]:
df.loc[df['genres'].notnull(),'genres'] = df.loc[df['genres'].notnull(),'genres'].apply(eval)

In [21]:
df.loc[df['crew'].notnull(),'crew'] = df.loc[df['crew'].notnull(),'crew'].apply(eval)

In [22]:
df.loc[df['cast'].notnull(),'cast'] = df.loc[df['cast'].notnull(),'cast'].apply(eval)

In [23]:
df['genres'][5]

[{'id': 16, 'name': 'Animation'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 10751, 'name': 'Family'}]

# 1. Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

In [24]:
df.loc[df['budget'] < 1000, 'budget'] = df.loc[df['budget'] >= 1000 , 'budget'].median()
df.loc[df['revenue'] < 1000, 'revenue'] = df.loc[df['revenue'] >= 1000 , 'budget'].median()

In [25]:
df.describe()

             budget       revenue
count  3.000000e+03  3.000000e+03
mean   2.708250e+07  6.703840e+07
std    3.492773e+07  1.373989e+08
min    2.500000e+03  1.404000e+03
25%    1.000000e+07  2.947600e+06
50%    1.645000e+07  1.680707e+07
75%    2.900000e+07  6.891920e+07
max    3.800000e+08  1.519558e+09

# profit

In [26]:
df['profit'] = df['revenue'] - df['budget']

In [27]:
df.head(3)

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit
0,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en,Hot Tub Time Machine 2,12314651,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",-1685349
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en,The Princess Diaries 2: Royal Engagement,95149435,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",55149435
2,3300000,"[{'id': 18, 'name': 'Drama'}]",tt2582802,en,Whiplash,13092000,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",9792000

In [28]:
highest_profit = df[df['profit'] == df['profit'].max()]  
t = highest_profit['original_title']
p = highest_profit['profit']
print( "Movie which earned highest profit is :")
highest_profit[['original_title','imdb_id','profit']]

Movie which earned highest profit is :

     original_title    imdb_id      profit
1761      Furious 7  tt2820852  1316249360

In [29]:
crew_list = highest_profit.iloc[0]['crew']

In [30]:
crew_list

[{'credit_id': '52fe4cc8c3a36847f823e681',
  'department': 'Production',
  'gender': 2,
  'id': 12835,
  'job': 'Producer',
  'name': 'Vin Diesel',
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e687',
  'department': 'Production',
  'gender': 2,
  'id': 11874,
  'job': 'Producer',
  'name': 'Neal H. Moritz',
  'profile_path': '/cNcsEYmoS4niCz3UkVAA09dUIob.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e68d',
  'department': 'Writing',
  'gender': 2,
  'id': 58191,
  'job': 'Writer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e693',
  'department': 'Writing',
  'gender': 0,
  'id': 8162,
  'job': 'Characters',
  'name': 'Gary Scott Thompson',
  'profile_path': '/e2dMfqFvRsOXgWZ1VToYLmos17y.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e699',
  'department': 'Directing',
  'gender': 2,
  'id': 2127,
  'job': 'Director',
  'name': 'James Wan',
  'profile_path': '/d1LSKfzi5J6QngWS7niN1zPJdud.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e6a7',
  'department': 'Camera',
  'gender': 2,
  'id': 58192,
  'job': 'Director of Photography',
  'name': 'Stephen F. Windon',
  'profile_path': None},
 {'credit_id': '5534714692514125dc002be4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1455610,
  'job': 'Animation',
  'name': 'Tony Mecca',
  'profile_path': None},
 {'credit_id': '554fa7b992514110bd002a9d',
  'department': 'Camera',
  'gender': 0,
  'id': 1421687,
  'job': 'Director of Photography',
  'name': 'Marc Spicer',
  'profile_path': None},
 {'credit_id': '554fa7cbc3a36822540047fd',
  'department': 'Production',
  'gender': 1,
  'id': 90635,
  'job': 'Executive Producer',
  'name': 'Samantha Vincent',
  'profile_path': None},
 {'credit_id': '554fa7d89251413fcf00773d',
  'department': 'Production',
  'gender': 0,
  'id': 84064,
  'job': 'Associate Producer',
  'name': 'F. Valentino Morales',
  'profile_path': '/w85eCnNP0VgmfV5NWyq2SvRGi2y.jpg'},
 {'credit_id': '554fa7f2c3a3682254004803',
  'department': 'Production',
  'gender': 2,
  'id': 8181,
  'job': 'Producer',
  'name': 'Michael Fottrell',
  'profile_path': None},
 {'credit_id': '554fa80292514110bd002aa8',
  'department': 'Production',
  'gender': 0,
  'id': 75826,
  'job': 'Producer',
  'name': 'Brandon Birtell',
  'profile_path': None},
 {'credit_id': '55ed993ac3a3682c62015607',
  'department': 'Editing',
  'gender': 0,
  'id': 1204244,
  'job': 'Editor',
  'name': 'Leigh Folsom Boyd',
  'profile_path': None},
 {'credit_id': '55ed994cc3a3687d3b00d64c',
  'department': 'Editing',
  'gender': 0,
  'id': 1204245,
  'job': 'Editor',
  'name': 'Dylan Highsmith',
  'profile_path': None},
 {'credit_id': '55ed995dc3a3682c5d016867',
  'department': 'Editing',
  'gender': 0,
  'id': 62813,
  'job': 'Editor',
  'name': 'Kirk M. Morri',
  'profile_path': None},
 {'credit_id': '55ed99739251413e41014641',
  'department': 'Editing',
  'gender': 2,
  'id': 6668,
  'job': 'Editor',
  'name': 'Christian Wagner',
  'profile_path': None},
 {'credit_id': '55ed99859251413e3a014aae',
  'department': 'Production',
  'gender': 1,
  'id': 9545,
  'job': 'Casting',
  'name': 'Anne McCarthy',
  'profile_path': None},
 {'credit_id': '55ed99a4c3a3682c5d016875',
  'department': 'Production',
  'gender': 0,
  'id': 1276602,
  'job': 'Casting',
  'name': 'Kellie Roy',
  'profile_path': None},
 {'credit_id': '55ed99c7c3a3682c5d01687e',
  'department': 'Art',
  'gender': 0,
  'id': 1445830,
  'job': 'Art Direction',
  'name': 'Jonathan Carlos',
  'profile_path': None},
 {'credit_id': '55ed99d89251413e32014a65',
  'department': 'Art',
  'gender': 2,
  'id': 62780,
  'job': 'Art Direction',
  'name': 'Alan Hook',
  'profile_path': None},
 {'credit_id': '55ed99e992514106d600d85e',
  'department': 'Art',
  'gender': 0,
  'id': 1493864,
  'job': 'Art Direction',
  'name': 'Jay Pelissier',
  'profile_path': None},
 {'credit_id': '55ed9a36c3a3682c700147e3',
  'department': 'Art',
  'gender': 1,
  'id': 1506359,
  'job': 'Art Department Coordinator',
  'name': 'Kelly Richardson',
  'profile_path': None},
 {'credit_id': '55ed9a52c3a3682c640130c3',
  'department': 'Art',
  'gender': 0,
  'id': 1506360,
  'job': 'Art Department Coordinator',
  'name': 'Courtney Cocherell',
  'profile_path': None},
 {'credit_id': '55ed9a6cc3a368090c004f9c',
  'department': 'Art',
  'gender': 0,
  'id': 1326651,
  'job': 'Assistant Art Director',
  'name': 'Elena Albanese',
  'profile_path': None},
 {'credit_id': '55ed9a96c3a3686f17003be1',
  'department': 'Art',
  'gender': 0,
  'id': 1405376,
  'job': 'Assistant Art Director',
  'name': 'Alex McCarroll',
  'profile_path': None},
 {'credit_id': '55ed9acbc3a3682c640130e4',
  'department': 'Art',
  'gender': 0,
  'id': 1338147,
  'job': 'Construction Coordinator',
  'name': 'Bruce Di Valerio',
  'profile_path': None},
 {'credit_id': '55ed9b03c3a3682c640130f5',
  'department': 'Art',
  'gender': 2,
  'id': 52600,
  'job': 'Production Design',
  'name': 'Bill Brzeski',
  'profile_path': None},
 {'credit_id': '55ed9b169251413e2f0145a8',
  'department': 'Art',
  'gender': 1,
  'id': 75391,
  'job': 'Set Decoration',
  'name': 'Danielle Berman',
  'profile_path': None},
 {'credit_id': '55ed9b29c3a3682c5d0168d9',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 2519,
  'job': 'Costume Design',
  'name': 'Sanja Milkovic Hays',
  'profile_path': None},
 {'credit_id': '55ed9bdac3a3682c62015698',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1439109,
  'job': 'Costume Supervisor',
  'name': 'Nava R. Sadan',
  'profile_path': None},
 {'credit_id': '55ed9c0bc3a3686f17003c45',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1439747,
  'job': 'Costume Supervisor',
  'name': 'Andrew Hunt',
  'profile_path': None},
 {'credit_id': '55ed9c3192514106d600d8e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506364,
  'job': 'Set Costumer',
  'name': 'Jim Alan Cook',
  'profile_path': None},
 {'credit_id': '55ed9c45c3a3682c5d016925',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1415019,
  'job': 'Set Costumer',
  'name': 'Shayne Allen Duhon',
  'profile_path': None},
 {'credit_id': '55ed9c579251413e32014af5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506365,
  'job': 'Set Costumer',
  'name': 'Empress Holley',
  'profile_path': None},
 {'credit_id': '55ed9c6d9251413e450148ff',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1413125,
  'job': 'Set Costumer',
  'name': 'Marina Marit',
  'profile_path': None},
 {'credit_id': '55ed9c8d92514106d600d8fb',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506366,
  'job': 'Set Costumer',
  'name': 'Les Morgan',
  'profile_path': None},
 {'credit_id': '55ed9cda9251413e2f014612',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1408293,
  'job': 'Hairstylist',
  'name': 'Linda D. Flowers',
  'profile_path': None},
 {'credit_id': '55ed9cf69251413e2f01461d',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1412767,
  'job': 'Hairstylist',
  'name': "Yesim 'Shimmy' Osman",
  'profile_path': None},
 {'credit_id': '55ed9d0ec3a3687d3b00d73a',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506367,
  'job': 'Hairstylist',
  'name': 'Jennifer Santiago',
  'profile_path': None},
 {'credit_id': '55ed9d2a9251413e3e0155d8',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1425409,
  'job': 'Hairstylist',
  'name': 'Rachel Solow',
  'profile_path': None},
 {'credit_id': '55ed9d4cc3a3682c620156ed',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1452643,
  'job': 'Hairstylist',
  'name': 'Roxane Griffin',
  'profile_path': None},
 {'credit_id': '55ed9d6fc3a3682c5d01696f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1309209,
  'job': 'Makeup Department Head',
  'name': 'James MacKinnon',
  'profile_path': None},
 {'credit_id': '55ed9d8cc3a368090c00504f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506368,
  'job': 'Makeup Artist',
  'name': 'Autumn Butler',
  'profile_path': None},
 {'credit_id': '55ed9da09251413e3a014b98',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1437798,
  'job': 'Makeup Artist',
  'name': "Roxy D'Alonzo",
  'profile_path': None},
 {'credit_id': '55ed9db79251413e3a014ba5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506369,
  'job': 'Makeup Artist',
  'name': 'Hee Soo Kwon',
  'profile_path': None},
 {'credit_id': '55ed9dce9251413e32014b4e',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1459196,
  'job': 'Makeup Artist',
  'name': 'Sarah Mays',
  'profile_path': None},
 {'credit_id': '55ed9de4c3a3687d3b00d775',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 15330,
  'job': 'Makeup Artist',
  'name': 'Paul Pattison',
  'profile_path': None},
 {'credit_id': '55ed9df99251413e3e015610',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1317667,
  'job': 'Makeup Artist',
  'name': 'Eleanor Sabaduquia',
  'profile_path': None},
 {'credit_id': '55ed9e1fc3a3687d3b00d77e',
  'department': 'Crew',
  'gender': 0,
  'id': 1414497,
  'job': 'Property Master',
  'name': 'Guillaume DeLouche',
  'profile_path': None},
 {'credit_id': '55ed9e3ac3a368090c005084',
  'department': 'Crew',
  'gender': 0,
  'id': 1464516,
  'job': 'Property Master',
  'name': 'Douglas T. Madison',
  'profile_path': None},
 {'credit_id': '55ed9f5d9251413e3e015662',
  'department': 'Crew',
  'gender': 2,
  'id': 57158,
  'job': 'Second Unit Cinematographer',
  'name': 'Igor Meglic',
  'profile_path': None},
 {'credit_id': '55ed9fa0c3a3682c6401320f',
  'department': 'Crew',
  'gender': 0,
  'id': 13670,
  'job': 'Second Unit Cinematographer',
  'name': 'Jacques Haitkin',
  'profile_path': None},
 {'credit_id': '55ed9fc59251413e32014bbc',
  'department': 'Lighting',
  'gender': 0,
  'id': 1437304,
  'job': 'Gaffer',
  'name': 'Michael Ambrose',
  'profile_path': None},
 {'credit_id': '55ed9fe79251413e410147e4',
  'department': 'Camera',
  'gender': 0,
  'id': 1506371,
  'job': 'Camera Operator',
  'name': 'Denise Bailie',
  'profile_path': None},
 {'credit_id': '55ed9ffa9251413e3a014c40',
  'department': 'Camera',
  'gender': 0,
  'id': 1506373,
  'job': 'Camera Operator',
  'name': 'Robert-James Bova',
  'profile_path': None},
 {'credit_id': '55eda0299251413e3a014c49',
  'department': 'Lighting',
  'gender': 0,
  'id': 1439108,
  'job': 'Rigging Gaffer',
  'name': 'Tom Fendley',
  'profile_path': None},
 {'credit_id': '55eda056c3a3682c7001494b',
  'department': 'Camera',
  'gender': 0,
  'id': 1434896,
  'job': 'Camera Operator',
  'name': 'Sarah Levy',
  'profile_path': None},
 {'credit_id': '55eda06e9251413e450149ee',
  'department': 'Camera',
  'gender': 2,
  'id': 74989,
  'job': 'Camera Operator',
  'name': 'Mark Emery Moore',
  'profile_path': '/mhjX0FuAXv6SeSLLFHpaaiQbx6P.jpg'},
 {'credit_id': '55eda082c3a3682c6b014009',
  'department': 'Camera',
  'gender': 2,
  'id': 1432918,
  'job': 'Camera Operator',
  'name': 'Daniel Nichols',
  'profile_path': None},
 {'credit_id': '55eda09d9251413e3e01569d',
  'department': 'Camera',
  'gender': 0,
  'id': 1439104,
  'job': 'Camera Operator',
  'name': 'Onofrio Nino Pansini',
  'profile_path': None},
 {'credit_id': '55eda0b59251413e3a014c6c',
  'department': 'Camera',
  'gender': 0,
  'id': 1408356,
  'job': 'Camera Operator',
  'name': 'David Richert',
  'profile_path': None},
 {'credit_id': '55eda0d1c3a3686f17003d58',
  'department': 'Camera',
  'gender': 2,
  'id': 1411271,
  'job': 'Camera Operator',
  'name': 'Michael J. Walker',
  'profile_path': None},
 {'credit_id': '55eda0f7c3a3687d3b00d81b',
  'department': 'Camera',
  'gender': 2,
  'id': 1378241,
  'job': 'Camera Operator',
  'name': 'Maurice K. McGuire',
  'profile_path': None},
 {'credit_id': '55eda1159251413e3e0156bd',
  'department': 'Camera',
  'gender': 0,
  'id': 1411842,
  'job': 'Camera Operator',
  'name': 'Richard Latham',
  'profile_path': None},
 {'credit_id': '55eda12c92514106d600da0a',
  'department': 'Camera',
  'gender': 0,
  'id': 1404739,
  'job': 'Helicopter Camera',
  'name': 'Steve Koster',
  'profile_path': None},
 {'credit_id': '55eda1939251413e3501498d',
  'department': 'Camera',
  'gender': 0,
  'id': 91122,
  'job': 'Helicopter Camera',
  'name': 'Dylan Goss',
  'profile_path': None},
 {'credit_id': '55eda1b39251413e3a014ca8',
  'department': 'Camera',
  'gender': 0,
  'id': 82169,
  'job': 'Steadicam Operator',
  'name': 'Geoffrey Haley',
  'profile_path': None},
 {'credit_id': '55eda1c7c3a3686f17003d8c',
  'department': 'Camera',
  'gender': 0,
  'id': 1419105,
  'job': 'Still Photographer',
  'name': 'Scott Garfield',
  'profile_path': None},
 {'credit_id': '55eda1dbc3a3686f17003d92',
  'department': 'Camera',
  'gender': 2,
  'id': 1395281,
  'job': 'Additional Camera',
  'name': 'Bob Gorelick',
  'profile_path': None},
 {'credit_id': '55eda200c3a3682c5d016a8f',
  'department': 'Camera',
  'gender': 0,
  'id': 1375920,
  'job': 'Additional Camera',
  'name': 'J. Christopher Campbell',
  'profile_path': None},
 {'credit_id': '55eda228c3a3682c64013295',
  'department': 'Lighting',
  'gender': 0,
  'id': 1403412,
  'job': 'Gaffer',
  'name': 'Dan Cornwall',
  'profile_path': None},
 {'credit_id': '55eda25f92514106d600da4b',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1442137,
  'job': 'Animation Supervisor',
  'name': 'Catherine Mullan',
  'profile_path': None},
 {'credit_id': '55eda292c3a3682c5d016ab2',
  'department': 'Sound',
  'gender': 0,
  'id': 1393405,
  'job': 'Music Editor',
  'name': 'Robb Boyd',
  'profile_path': None},
 {'credit_id': '55eda2a9c3a3682c6b014075',
  'department': 'Sound',
  'gender': 0,
  'id': 1328758,
  'job': 'Music Editor',
  'name': 'Matthew Llewellyn',
  'profile_path': None},
 {'credit_id': '55eda2c89251413e45014a6d',
  'department': 'Directing',
  'gender': 0,
  'id': 1389138,
  'job': 'Script Supervisor',
  'name': 'Jody Blose',
  'profile_path': None},
 {'credit_id': '55eda305c3a3682c700149c1',
  'department': 'Directing',
  'gender': 0,
  'id': 1408365,
  'job': 'Script Supervisor',
  'name': 'Brenda K. Wachel',
  'profile_path': None},
 {'credit_id': '55eda32dc3a3686f17003ddd',
  'department': 'Crew',
  'gender': 2,
  'id': 8167,
  'job': 'Thanks',
  'name': 'Paul Walker',
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'credit_id': '55eda3b592514106d600da94',
  'department': 'Editing',
  'gender': 0,
  'id': 1400354,
  'job': 'Digital Intermediate',
  'name': 'Amy Pawlowski',
  'profile_path': None},
 {'credit_id': '55eda3d792514106d600da9b',
  'department': 'Editing',
  'gender': 0,
  'id': 110262,
  'job': 'First Assistant Editor',
  'name': 'Richard Conkling',
  'profile_path': None},
 {'credit_id': '55eda3edc3a3686f17003e0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1194885,
  'job': 'First Assistant Editor',
  'name': 'Dave  Cory',
  'profile_path': None},
 {'credit_id': '55eda4169251413e410148ec',
  'department': 'Editing',
  'gender': 0,
  'id': 1439749,
  'job': 'First Assistant Editor',
  'name': 'Laura Steiger',
  'profile_path': None},
 {'credit_id': '55eda48092514106d600daba',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1506377,
  'job': 'Animation Supervisor',
  'name': 'Daniel Barrett',
  'profile_path': '/pplTJP3gCWmP3SMDrXjOt1579MV.jpg'},
 {'credit_id': '55eda5109251413e32014cf0',
  'department': 'Sound',
  'gender': 0,
  'id': 12562,
  'job': 'ADR & Dubbing',
  'name': 'Anna MacKenzie',
  'profile_path': None},
 {'credit_id': '55eda51ac3a3686f17003e52',
  'department': 'Editing',
  'gender': 0,
  'id': 12562,
  'job': 'Dialogue Editor',
  'name': 'Anna MacKenzie',
  'profile_path': None},
 {'credit_id': '55eda539c3a368090c0051c2',
  'department': 'Editing',
  'gender': 0,
  'id': 1342658,
  'job': 'Dialogue Editor',
  'name': 'Frederick H. Stahly',
  'profile_path': None},
 {'credit_id': '55eda56a9251413e45014adf',
  'department': 'Sound',
  'gender': 2,
  'id': 1077782,
  'job': 'Foley',
  'name': 'Gary A. Hecker',
  'profile_path': '/qyBUauN3XIS2Mlus3OdGCmrUo0S.jpg'},
 {'credit_id': '55eda58292514106d600daf4',
  'department': 'Sound',
  'gender': 0,
  'id': 1367362,
  'job': 'Foley',
  'name': 'Rick Owens',
  'profile_path': None},
 {'credit_id': '55eda59ac3a3682c5d016b50',
  'department': 'Sound',
  'gender': 0,
  'id': 1236340,
  'job': 'Foley',
  'name': 'Dylan Tuomy-Wilhoit',
  'profile_path': None},
 {'credit_id': '55eda5b09251413e45014af1',
  'department': 'Sound',
  'gender': 0,
  'id': 548445,
  'job': 'Foley',
  'name': 'Jeffrey Wilhoit',
  'profile_path': None},
 {'credit_id': '55eda7169251413e45014b3b',
  'department': 'Sound',
  'gender': 2,
  'id': 7239,
  'job': 'Sound Designer',
  'name': 'Peter Brown',
  'profile_path': None},
 {'credit_id': '55eda73d9251413e4101498c',
  'department': 'Sound',
  'gender': 0,
  'id': 1392083,
  'job': 'Sound Designer',
  'name': 'Ann Scibelli',
  'profile_path': None},
 {'credit_id': '55eda779c3a3682c70014abc',
  'department': 'Sound',
  'gender': 0,
  'id': 1413453,
  'job': 'Sound Effects Editor',
  'name': 'Stephen P. Robinson',
  'profile_path': None},
 {'credit_id': '55eda7989251413e3e015838',
  'department': 'Sound',
  'gender': 0,
  'id': 1394131,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Jon Taylor',
  'profile_path': None},
 {'credit_id': '55eda7afc3a3686f17003ebf',
  'department': 'Sound',
  'gender': 0,
  'id': 1394130,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Frank A. Monta√±o',
  'profile_path': None},
 {'credit_id': '55eda7d79251413e32014e11',
  'department': 'Sound',
  'gender': 0,
  'id': 1309884,
  'job': 'Supervising Sound Editor',
  'name': 'Joe Dzuban',
  'profile_path': None},
 {'credit_id': '570bd40dc3a36802a30002d9',
  'department': 'Art',
  'gender': 0,
  'id': 1424153,
  'job': 'Supervising Art Director',
  'name': 'Desma Murphy',
  'profile_path': None},
 {'credit_id': '5668cc7a92514174040040f2',
  'department': 'Sound',
  'gender': 2,
  'id': 6041,
  'job': 'Original Music Composer',
  'name': 'Brian Tyler',
  'profile_path': '/22QWiNJj03amY6GT1QPUs7dbdcB.jpg'},
 {'credit_id': '58ebe1fa925141281008e943',
  'department': 'Production',
  'gender': 2,
  'id': 58191,
  'job': 'Executive Producer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'}]

In [31]:
producer_list = []
director_list = [] 
for i in crew_list :
  if i['job'] == 'Producer':
    producer_list.append(i['name'])
  elif i['job'] == 'Director' :
    director_list.append(i['name'])

print(f"Name of producers :{producer_list} \nName of Directors :{director_list}")

Name of producers :['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']
Name of Directors :['James Wan']

In [32]:
cast_list = highest_profit.iloc[0]['cast']
cast_list

[{'cast_id': 17,
  'character': 'Dominic Toretto',
  'credit_id': '5431dfd10e0a265915002c34',
  'gender': 2,
  'id': 12835,
  'name': 'Vin Diesel',
  'order': 0,
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'cast_id': 19,
  'character': "Brian O'Conner",
  'credit_id': '5431dfe4c3a3681143002b98',
  'gender': 2,
  'id': 8167,
  'name': 'Paul Walker',
  'order': 1,
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'cast_id': 18,
  'character': 'Hobbs',
  'credit_id': '5431dfdbc3a36831a6004376',
  'gender': 2,
  'id': 18918,
  'name': 'Dwayne Johnson',
  'order': 2,
  'profile_path': '/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg'},
 {'cast_id': 20,
  'character': 'Letty',
  'credit_id': '5431dfeec3a36811ef002c75',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 3,
  'profile_path': '/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg'},
 {'cast_id': 28,
  'character': 'Roman',
  'credit_id': '5431e0310e0a2656e2002c95',
  'gender': 2,
  'id': 8169,
  'name': 'Tyrese Gibson',
  'order': 4,
  'profile_path': '/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg'},
 {'cast_id': 31,
  'character': "Tej (as Chris 'Ludacris' Bridges)",
  'credit_id': '5431e0520e0a2658b2002c3c',
  'gender': 2,
  'id': 8171,
  'name': 'Ludacris',
  'order': 5,
  'profile_path': '/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg'},
 {'cast_id': 24,
  'character': 'Mia',
  'credit_id': '5431e00dc3a36811ef002c7e',
  'gender': 1,
  'id': 22123,
  'name': 'Jordana Brewster',
  'order': 6,
  'profile_path': '/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg'},
 {'cast_id': 25,
  'character': 'Jakande',
  'credit_id': '5431e015c3a36831a90040da',
  'gender': 2,
  'id': 938,
  'name': 'Djimon Hounsou',
  'order': 7,
  'profile_path': '/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg'},
 {'cast_id': 30,
  'character': 'Kiet',
  'credit_id': '5431e04a0e0a26464300432c',
  'gender': 2,
  'id': 57207,
  'name': 'Tony Jaa',
  'order': 8,
  'profile_path': '/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg'},
 {'cast_id': 21,
  'character': 'Kara',
  'credit_id': '5431dff40e0a2646490043fa',
  'gender': 0,
  'id': 997887,
  'name': 'Ronda Rousey',
  'order': 9,
  'profile_path': '/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg'},
 {'cast_id': 27,
  'character': 'Ramsey',
  'credit_id': '5431e026c3a36831ac004333',
  'gender': 1,
  'id': 1251069,
  'name': 'Nathalie Emmanuel',
  'order': 10,
  'profile_path': '/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg'},
 {'cast_id': 22,
  'character': 'Mr. Nobody',
  'credit_id': '5431dffa0e0a265872002bdf',
  'gender': 2,
  'id': 6856,
  'name': 'Kurt Russell',
  'order': 11,
  'profile_path': '/rlnFuNkisPpuypARI7QaGCmOY6V.jpg'},
 {'cast_id': 16,
  'character': 'Deckard Shaw',
  'credit_id': '5431dfc70e0a265872002bd5',
  'gender': 2,
  'id': 976,
  'name': 'Jason Statham',
  'order': 12,
  'profile_path': '/PhWiWgasncGWD9LdbsGcmxkV4r.jpg'},
 {'cast_id': 39,
  'character': 'Han',
  'credit_id': '554fa75f92514110bd002a7d',
  'gender': 2,
  'id': 61697,
  'name': 'Sung Kang',
  'order': 13,
  'profile_path': '/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg'},
 {'cast_id': 38,
  'character': 'Gisele',
  'credit_id': '554fa7439251413e40005aa1',
  'gender': 1,
  'id': 90633,
  'name': 'Gal Gadot',
  'order': 14,
  'profile_path': '/34kHAyBaBhq2kUrmhM15paEBuuI.jpg'},
 {'cast_id': 15,
  'character': 'Sean Boswell',
  'credit_id': '5431dfbb0e0a265915002c2d',
  'gender': 2,
  'id': 155,
  'name': 'Lucas Black',
  'order': 15,
  'profile_path': '/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg'},
 {'cast_id': 23,
  'character': 'Elena',
  'credit_id': '5431e003c3a36811ef002c7c',
  'gender': 1,
  'id': 73269,
  'name': 'Elsa Pataky',
  'order': 16,
  'profile_path': '/c1km2kqasJT9GTISMbBZpp3jbuR.jpg'},
 {'cast_id': 35,
  'character': 'Hector',
  'credit_id': '554fa677c3a3687b7d002468',
  'gender': 2,
  'id': 53252,
  'name': 'Noel Gugliemi',
  'order': 17,
  'profile_path': '/mI5urNyZJAzIGxelTjBkm624DkB.jpg'},
 {'cast_id': 37,
  'character': 'Sheppard',
  'credit_id': '554fa6f19251413ea10004fc',
  'gender': 2,
  'id': 222906,
  'name': 'John Brotherton',
  'order': 18,
  'profile_path': '/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg'},
 {'cast_id': 34,
  'character': 'Owen Shaw',
  'credit_id': '554fa651c3a3681870005275',
  'gender': 2,
  'id': 114019,
  'name': 'Luke Evans',
  'order': 19,
  'profile_path': '/1d31uDYub8TaLOPWfgX78OotduD.jpg'},
 {'cast_id': 36,
  'character': 'Safar',
  'credit_id': '554fa6d7c3a3685221000283',
  'gender': 2,
  'id': 492791,
  'name': 'Ali Fazal',
  'order': 20,
  'profile_path': '/AmT132VCz3InJBAQQPJnqqgsQsB.jpg'},
 {'cast_id': 145,
  'character': 'Jack',
  'credit_id': '59a8b72092514157c601fb92',
  'gender': 0,
  'id': 1880145,
  'name': 'Miller Kimsey',
  'order': 21,
  'profile_path': None},
 {'cast_id': 146,
  'character': 'Jack',
  'credit_id': '59a8b72b925141579d020797',
  'gender': 0,
  'id': 1880146,
  'name': 'Charlie Kimsey',
  'order': 22,
  'profile_path': None},
 {'cast_id': 133,
  'character': 'Samantha Hobbs',
  'credit_id': '56417cfec3a3685be2001846',
  'gender': 1,
  'id': 1533850,
  'name': 'Eden Estrella',
  'order': 23,
  'profile_path': '/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg'},
 {'cast_id': 147,
  'character': 'Letty Fan',
  'credit_id': '59a8b787c3a36874d5007d12',
  'gender': 2,
  'id': 1534800,
  'name': 'Gentry White',
  'order': 24,
  'profile_path': '/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg'},
 {'cast_id': 26,
  'character': 'Female Racer',
  'credit_id': '5431e01c0e0a265834002c97',
  'gender': 1,
  'id': 1364893,
  'name': 'Iggy Azalea',
  'order': 25,
  'profile_path': '/KG5skDx5WeGDijkUUQnmOP0crG.jpg'},
 {'cast_id': 148,
  'character': 'Male Racer',
  'credit_id': '59a8b7afc3a3683d0701b1ad',
  'gender': 0,
  'id': 1161711,
  'name': 'Jon Lee Brody',
  'order': 26,
  'profile_path': '/u1agQE1nYgt2LOijksYJMPYxpKh.jpg'},
 {'cast_id': 135,
  'character': 'Race Starter',
  'credit_id': '56c259c89251414a9b000865',
  'gender': 1,
  'id': 1578220,
  'name': 'Levy Tran',
  'order': 27,
  'profile_path': '/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg'},
 {'cast_id': 132,
  'character': 'Hot Teacher',
  'credit_id': '56417cc592514128af001862',
  'gender': 0,
  'id': 118593,
  'name': 'Anna Colwell',
  'order': 28,
  'profile_path': '/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg'},
 {'cast_id': 149,
  'character': 'Doctor',
  'credit_id': '59a8b80e92514157ab0206fc',
  'gender': 0,
  'id': 1880147,
  'name': 'Viktor Hernandez',
  'order': 29,
  'profile_path': None},
 {'cast_id': 150,
  'character': 'Priest',
  'credit_id': '59a8b84092514157c601fce8',
  'gender': 2,
  'id': 80619,
  'name': 'Steve Coulter',
  'order': 30,
  'profile_path': '/v1cwS9Ia89pO154Wje3m4IxuI3.jpg'},
 {'cast_id': 130,
  'character': 'Merc Tech',
  'credit_id': '56417c3092514128a6001a15',
  'gender': 0,
  'id': 97844,
  'name': 'Robert Pralgo',
  'order': 31,
  'profile_path': '/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg'},
 {'cast_id': 151,
  'character': 'Weapons Tech',
  'credit_id': '59a8b888c3a3683ce601e3aa',
  'gender': 0,
  'id': 1381712,
  'name': 'Antwan Mills',
  'order': 32,
  'profile_path': '/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg'},
 {'cast_id': 152,
  'character': 'Billionaire',
  'credit_id': '59a8b8bac3a36874d5007ea3',
  'gender': 0,
  'id': 1880148,
  'name': 'J.J. Phillips',
  'order': 33,
  'profile_path': None},
 {'cast_id': 153,
  'character': 'Dominican Priest',
  'credit_id': '59a8b8ccc3a3683c8701fa73',
  'gender': 0,
  'id': 1880149,
  'name': 'Jorge Ferragut',
  'order': 34,
  'profile_path': None},
 {'cast_id': 154,
  'character': 'Hana',
  'credit_id': '59a8b8e3c3a36874d5007ec7',
  'gender': 0,
  'id': 1440699,
  'name': 'Sara Sohn',
  'order': 35,
  'profile_path': '/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg'},
 {'cast_id': 155,
  'character': 'Merc Driver (as Ben Blankenship)',
  'credit_id': '59a8b904c3a3683c7a02381c',
  'gender': 0,
  'id': 1093707,
  'name': 'Benjamin Blankenship',
  'order': 36,
  'profile_path': '/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg'},
 {'cast_id': 156,
  'character': 'DJ',
  'credit_id': '59a8b953c3a36876710081c2',
  'gender': 0,
  'id': 1880150,
  'name': 'D.J. Hapa',
  'order': 37,
  'profile_path': None},
 {'cast_id': 140,
  'character': 'DJ',
  'credit_id': '58eee68c92514142020018f0',
  'gender': 0,
  'id': 224092,
  'name': 'T-Pain',
  'order': 38,
  'profile_path': None},
 {'cast_id': 157,
  'character': 'Drone Tech',
  'credit_id': '59a8b98892514157ee01f2d9',
  'gender': 2,
  'id': 54792,
  'name': 'Brian Mahoney',
  'order': 39,
  'profile_path': '/v6pTsqgOHE5TldFV63Kr44idQNe.jpg'},
 {'cast_id': 131,
  'character': 'Jasmine',
  'credit_id': '56417c7b92514128a90018fb',
  'gender': 1,
  'id': 1128522,
  'name': 'Brittney Alger',
  'order': 40,
  'profile_path': '/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg'},
 {'cast_id': 158,
  'character': 'Mando',
  'credit_id': '59a8b9ad92514157ab020902',
  'gender': 0,
  'id': 1451616,
  'name': 'Romeo Santos',
  'order': 41,
  'profile_path': '/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg'},
 {'cast_id': 159,
  'character': 'Advisor',
  'credit_id': '59a8b9ca925141579d020ab6',
  'gender': 1,
  'id': 78804,
  'name': 'Jocelin Donahue',
  'order': 42,
  'profile_path': '/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg'},
 {'cast_id': 160,
  'character': 'Field Reporter',
  'credit_id': '59a8b9da9251415808021296',
  'gender': 0,
  'id': 1880151,
  'name': 'Stephanie Langston',
  'order': 43,
  'profile_path': None},
 {'cast_id': 161,
  'character': 'Cop',
  'credit_id': '59a8b9f192514157a5020874',
  'gender': 0,
  'id': 1448173,
  'name': 'Jorge-Luis Pallo',
  'order': 44,
  'profile_path': '/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg'},
 {'cast_id': 143,
  'character': 'Leo (uncredited / archive)',
  'credit_id': '58eee6b8925141423500180f',
  'gender': 2,
  'id': 96321,
  'name': 'Tego Calder√≥n',
  'order': 45,
  'profile_path': '/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg'},
 {'cast_id': 142,
  'character': 'Neela (uncredited / archive)',
  'credit_id': '58eee6ab92514141ff001971',
  'gender': 1,
  'id': 116277,
  'name': 'Nathalie Kelley',
  'order': 46,
  'profile_path': '/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg'},
 {'cast_id': 29,
  'character': 'Twinkie (uncredited)',
  'credit_id': '5431e03e0e0a265872002bf2',
  'gender': 0,
  'id': 58197,
  'name': 'Shad Moss',
  'order': 47,
  'profile_path': '/A1rHY9B5R9cIQshClcJxBYINg1m.jpg'},
 {'cast_id': 144,
  'character': 'Santos (uncredited / archive)',
  'credit_id': '58eee6c492514141f70019b8',
  'gender': 0,
  'id': 90634,
  'name': 'Don Omar',
  'order': 48,
  'profile_path': '/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg'},
 {'cast_id': 141,
  'character': 'Race Wars Racer (uncredited)',
  'credit_id': '58eee698c3a36826510017dc',
  'gender': 0,
  'id': 1563213,
  'name': 'Klement Tinaj',
  'order': 49,
  'profile_path': None},
 {'cast_id': 139,
  'character': "Brian O'Conner (uncredited)",
  'credit_id': '58eee621c3a368265e001729',
  'gender': 0,
  'id': 1795034,
  'name': 'Caleb Walker',
  'order': 50,
  'profile_path': None},
 {'cast_id': 45,
  'character': "Brian O'Connor (uncredited)",
  'credit_id': '5589e3fd925141569c00003e',
  'gender': 2,
  'id': 1480862,
  'name': 'Cody Walker',
  'order': 51,
  'profile_path': '/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg'}]

In [33]:
print('Actors :')
#actors = pd.DataFrame( columns= ['id','Name'])
for i in cast_list :
  print(f"id {i['id']} : {i['name']}")

Actors :
id 12835 : Vin Diesel
id 8167 : Paul Walker
id 18918 : Dwayne Johnson
id 17647 : Michelle Rodriguez
id 8169 : Tyrese Gibson
id 8171 : Ludacris
id 22123 : Jordana Brewster
id 938 : Djimon Hounsou
id 57207 : Tony Jaa
id 997887 : Ronda Rousey
id 1251069 : Nathalie Emmanuel
id 6856 : Kurt Russell
id 976 : Jason Statham
id 61697 : Sung Kang
id 90633 : Gal Gadot
id 155 : Lucas Black
id 73269 : Elsa Pataky
id 53252 : Noel Gugliemi
id 222906 : John Brotherton
id 114019 : Luke Evans
id 492791 : Ali Fazal
id 1880145 : Miller Kimsey
id 1880146 : Charlie Kimsey
id 1533850 : Eden Estrella
id 1534800 : Gentry White
id 1364893 : Iggy Azalea
id 1161711 : Jon Lee Brody
id 1578220 : Levy Tran
id 118593 : Anna Colwell
id 1880147 : Viktor Hernandez
id 80619 : Steve Coulter
id 97844 : Robert Pralgo
id 1381712 : Antwan Mills
id 1880148 : J.J. Phillips
id 1880149 : Jorge Ferragut
id 1440699 : Sara Sohn
id 1093707 : Benjamin Blankenship
id 1880150 : D.J. Hapa
id 224092 : T-Pain
id 54792 : Brian Mahoney
id 1128522 : Brittney Alger
id 1451616 : Romeo Santos
id 78804 : Jocelin Donahue
id 1880151 : Stephanie Langston
id 1448173 : Jorge-Luis Pallo
id 96321 : Tego Calder√≥n
id 116277 : Nathalie Kelley
id 58197 : Shad Moss
id 90634 : Don Omar
id 1563213 : Klement Tinaj
id 1795034 : Caleb Walker
id 1480862 : Cody Walker

## 2. Movies of which language made the highest average ROI (return on investment)?

In [34]:
df['roi'] = 100 * (df['profit']  / df['budget'])

In [35]:
df.columns

Index(['budget', 'genres', 'imdb_id', 'original_language', 'original_title',
       'revenue', 'cast', 'crew', 'profit', 'roi'],
      dtype='object')

In [36]:
df.head(2)

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit,roi
0,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en,Hot Tub Time Machine 2,12314651,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",-1685349,-12.038207
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en,The Princess Diaries 2: Royal Engagement,95149435,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",55149435,137.873588

In [37]:
roi_lang_df = df.groupby('original_language')['roi'].mean().reset_index()
roi_lang_df.rename(columns = {'roi':'mean of roi'}, inplace = True)

In [38]:
roi_lang_df

   original_language   mean of roi
0                 ar    -91.807009
1                 bn    -96.739429
2                 cn     86.002479
3                 cs    -99.894267
4                 da     24.702661
5                 de    496.288571
6                 el   5198.013245
7                 en    929.857027
8                 es    103.433478
9                 fa      3.235168
10                fi    -30.319235
11                fr     51.738297
12                he    456.292450
13                hi    249.167911
14                hu    -95.535384
15                id    -41.617578
16                it     22.136747
17                ja    122.592623
18                ko  11277.633936
19                ml    370.833333
20                mr    193.333333
21                nb     18.847943
22                nl    -24.142008
23                no     24.155275
24                pl    395.816987
25                pt    -29.291459
26                ro    -62.182109
27                ru    112.216835
28                sr   3190.000000
29                sv     25.064775
30                ta    158.864249
31                te    440.076812
32                tr    558.596201
33                ur    350.673773
34                vi    -50.846154
35                zh    308.429313

In [39]:
max_avg_roi = roi_lang_df['mean of roi'].max()
lang_max_roi = roi_lang_df[roi_lang_df['mean of roi'] == max_avg_roi].loc[:,['original_language','mean of roi']]
lang_max_roi

   original_language   mean of roi
18                ko  11277.633936

# 3. Find out the unique genres of movies in this dataset.

In [40]:
genres_not_null = df[df['genres'].notnull()]
genres_not_null.head(3)

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit,roi
0,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en,Hot Tub Time Machine 2,12314651,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",-1685349,-12.038207
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en,The Princess Diaries 2: Royal Engagement,95149435,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",55149435,137.873588
2,3300000,"[{'id': 18, 'name': 'Drama'}]",tt2582802,en,Whiplash,13092000,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",9792000,296.727273

In [41]:
genres_not_null.iloc[100]['genres']

[{'id': 28, 'name': 'Action'},
 {'id': 53, 'name': 'Thriller'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 80, 'name': 'Crime'},
 {'id': 27, 'name': 'Horror'}]

In [42]:
for elem in genres_not_null['genres'][0:5] :
  print(type(elem))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>

In [43]:
for  elem in genres_not_null[0:5].iterrows() :
   print(type(elem))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>

In [44]:
genres_list = []

for index,row in genres_not_null.iterrows() :
    for elem in row['genres']:
      genres_list.append(elem['name'])
print(genres_list)

['Comedy', 'Comedy', 'Drama', 'Family', 'Romance', 'Drama', 'Thriller', 'Drama', 'Action', 'Thriller', 'Animation', 'Adventure', 'Family', 'Horror', 'Thriller', 'Documentary', 'Action', 'Comedy', 'Music', 'Family', 'Adventure', 'Comedy', 'Music', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Crime', 'Action', 'Thriller', 'Science Fiction', 'Mystery', 'Action', 'Crime', 'Drama', 'Horror', 'Thriller', 'Drama', 'Romance', 'Comedy', 'Romance', 'Action', 'Thriller', 'Crime', 'Adventure', 'Family', 'Science Fiction', 'Horror', 'Thriller', 'Thriller', 'Horror', 'Thriller', 'Mystery', 'Foreign', 'Horror', 'Comedy', 'Comedy', 'Horror', 'Mystery', 'Thriller', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Animation', 'Action', 'Adventure', 'Crime', 'Thriller', 'Drama', 'Comedy', 'Mystery', 'Drama', 'Thriller', 'Fantasy', 'Action', 'Adventure', 'Horror', 'Action', 'Comedy', 'Crime', 'Thriller', 'Action', 'Crime', 'Thriller', 'Comedy', 'Romance', 'Action', 'Drama', 'Science Fiction', 'Thriller', 'Thriller', 'War', 'Western', 'Action', 'Documentary', 'Crime', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Crime', 'Drama', 'Mystery', 'Romance', 'Thriller', 'Animation', 'Family', 'Comedy', 'Adventure', 'Crime', 'Drama', 'Mystery', 'Western', 'Drama', 'Comedy', 'Science Fiction', 'Action', 'Adventure', 'Thriller', 'Romance', 'Drama', 'Comedy', 'Adventure', 'Comedy', 'Adventure', 'Family', 'Drama', 'Family', 'Romance', 'Action', 'Comedy', 'Drama', 'Romance', 'Comedy', 'Drama', 'Action', 'Crime', 'Fantasy', 'Music', 'Romance', 'Action', 'Adventure', 'Comedy', 'Adventure', 'Action', 'Thriller', 'Drama', 'Thriller', 'Fantasy', 'Crime', 'Drama', 'Horror', 'Thriller', 'Drama', 'Adventure', 'Action', 'Crime', 'Comedy', 'Drama', 'Crime', 'Drama', 'Action', 'Crime', 'Drama', 'Thriller', 'Drama', 'Mystery', 'Thriller', 'Fantasy', 'Drama', 'Comedy', 'Music', 'Crime', 'Documentary', 'Crime', 'Drama', 'Horror', 'Comedy', 'Drama', 'Romance', 'Foreign', 'Comedy', 'Crime', 'Drama', 'Action', 'Thriller', 'Horror', 'Thriller', 'Action', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'Horror', 'Mystery', 'Thriller', 'Thriller', 'Science Fiction', 'Horror', 'Mystery', 'Action', 'Adventure', 'Drama', 'Mystery', 'Science Fiction', 'Thriller', 'Drama', 'Crime', 'Action', 'Comedy', 'Thriller', 'Drama', 'History', 'Drama', 'Thriller', 'Mystery', 'Romance', 'Action', 'Crime', 'Drama', 'War', 'Adventure', 'Drama', 'Romance', 'Drama', 'History', 'Thriller', 'Drama', 'Mystery', 'Drama', 'Action', 'Comedy', 'Thriller', 'Romance', 'Fantasy', 'Drama', 'Animation', 'Comedy', 'Adventure', 'Family', 'Action', 'Crime', 'Drama', 'Action', 'Thriller', 'Science Fiction', 'Crime', 'Horror', 'Drama', 'Romance', 'Action', 'Comedy', 'Crime', 'Foreign', 'Drama', 'Comedy', 'Drama', 'Drama', 'Action', 'Drama', 'History', 'War', 'Drama', 'Comedy', 'Romance', 'Drama', 'Adventure', 'Romance', 'Action', 'Comedy', 'Crime', 'Romance', 'Comedy', 'Romance', 'Drama', 'Thriller', 'Drama', 'Adventure', 'Action', 'History', 'Comedy', 'Drama', 'Romance', 'Adventure', 'Fantasy', 'Action', 'Action', 'Comedy', 'Drama', 'Action', 'Adventure', 'Comedy', 'Drama', 'Romance', 'Crime', 'Action', 'Comedy', 'Action', 'Comedy', 'Crime', 'Thriller', 'Adventure', 'Animation', 'Drama', 'Family', 'Action', 'Comedy', 'Crime', 'Mystery', 'Thriller', 'Action', 'Crime', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'War', 'Action', 'Adventure', 'Comedy', 'Horror', 'Drama', 'Thriller', 'Mystery', 'Horror', 'Thriller', 'Drama', 'Comedy', 'Drama', 'Thriller', 'Documentary', 'History', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Adventure', 'Comedy', 'Drama', 'Drama', 'Family', 'Comedy', 'Thriller', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Drama', 'Music', 'Romance', 'Drama', 'Romance', 'Drama', 'Comedy', 'Drama', 'Horror', 'Crime', 'Thriller', 'Drama', 'Mystery', 'Romance', 'Comedy', 'Crime', 'Action', 'Science Fiction', 'Drama', 'Comedy', 'Family', 'Thriller', 'Adventure', 'Drama', 'Adventure', 'Drama', 'Western', 'Documentary', 'Drama', 'Fantasy', 'Horror', 'Thriller', 'Action', 'Crime', 'Thriller', 'Adventure', 'Fantasy', 'Animation', 'Family', 'Action', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Drama', 'Thriller', 'Crime', 'Action', 'Western', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Drama', 'Comedy', 'Comedy', 'Drama', 'Thriller', 'Horror', 'Fantasy', 'Action', 'Comedy', 'Science Fiction', 'Romance', 'Documentary', 'Music', 'Crime', 'Drama', 'Horror', 'Thriller', 'Mystery', 'Comedy', 'Crime', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Comedy', 'Crime', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Action', 'Drama', 'Thriller', 'Crime', 'Mystery', 'Adventure', 'Comedy', 'Action', 'Crime', 'Thriller', 'Horror', 'Science Fiction', 'Thriller', 'Drama', 'Romance', 'Action', 'Adventure', 'Thriller', 'War', 'Adventure', 'Action', 'Thriller', 'Thriller', 'Crime', 'Drama', 'Drama', 'Comedy', 'Romance', 'Adventure', 'Drama', 'Action', 'Comedy', 'Drama', 'Fantasy', 'Romance', 'Drama', 'Crime', 'Comedy', 'Drama', 'Mystery', 'Animation', 'Family', 'Drama', 'Comedy', 'Horror', 'Thriller', 'Science Fiction', 'Romance', 'Comedy', 'Drama', 'Comedy', 'Action', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Drama', 'Drama', 'Horror', 'Action', 'Thriller', 'Crime', 'Action', 'Comedy', 'Drama', 'Drama', 'Crime', 'Comedy', 'Family', 'Fantasy', 'Music', 'Comedy', 'Drama', 'Romance', 'Science Fiction', 'Animation', 'Comedy', 'Family', 'Animation', 'Comedy', 'Family', 'Horror', 'Comedy', 'Romance', 'Crime', 'Drama', 'Thriller', 'Crime', 'Drama', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Family', 'Fantasy', 'Fantasy', 'Horror', 'Science Fiction', 'Western', 'Adventure', 'Horror', 'Comedy', 'Horror', 'Thriller', 'Adventure', 'Action', 'Comedy', 'Family', 'Action', 'Thriller', 'Crime', 'Drama', 'Comedy', 'Crime', 'Fantasy', 'Animation', 'Family', 'Action', 'Comedy', 'Comedy', 'Documentary', 'Drama', 'History', 'War', 'Comedy', 'Romance', 'Comedy', 'Drama', 'Romance', 'Thriller', 'Mystery', 'Comedy', 'Action', 'Adventure', 'Drama', 'History', 'Fantasy', 'Thriller', 'Action', 'Crime', 'Drama', 'Romance', 'Adventure', 'Western', 'Drama', 'Romance', 'Action', 'Adventure', 'Comedy', 'Drama', 'Romance', 'Comedy', 'Drama', 'Western', 'Documentary', 'Action', 'Adventure', 'Drama', 'History', 'Adventure', 'Family', 'Horror', 'Comedy', 'Comedy', 'Fantasy', 'Drama', 'Thriller', 'Mystery', 'Romance', 'Drama', 'Romance', 'Comedy', 'Music', 'Action', 'Drama', 'Animation', 'Music', 'Family', 'Animation', 'Comedy', 'Drama', 'Romance', 'Romance', 'Comedy', 'Horror', 'Comedy', 'Adventure', 'Romance', 'Romance', 'Comedy', 'Crime', 'Fantasy', 'Drama', 'History', 'War', 'Action', 'Crime', 'Thriller', 'Mystery', 'Comedy', 'Action', 'Adventure', 'Comedy', 'Horror', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Adventure', 'Drama', 'Drama', 'Action', 'Western', 'Music', 'Romance', 'Action', 'Animation', 'Science Fiction', 'Drama', 'Drama', 'Family', 'Comedy', 'Drama', 'Romance', 'Science Fiction', 'Drama', 'Thriller', 'Crime', 'Drama', 'Adventure', 'Drama', 'Comedy', 'Adventure', 'Action', 'Family', 'Documentary', 'Foreign', 'Music', 'Family', 'Comedy', 'Comedy', 'Action', 'Thriller', 'Family', 'Comedy', 'Comedy', 'Romance', 'Documentary', 'Horror', 'Fantasy', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Romance', 'Drama', 'Drama', 'Crime', 'Thriller', 'Horror', 'Thriller', 'Horror', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Science Fiction', 'Thriller', 'Adventure', 'Horror', 'Thriller', 'Thriller', 'Comedy', 'Crime', 'Romance', 'Action', 'Drama', 'Animation', 'Drama', 'Family', 'Fantasy', 'Comedy', 'Drama', 'Romance', 'Crime', 'Drama', 'Thriller', 'Drama', 'War', 'Action', 'Drama', 'Foreign', 'History', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Fantasy', 'Science Fiction', 'Drama', 'Action', 'Crime', 'Drama', 'Comedy', 'Fantasy', 'Action', 'Comedy', 'Science Fiction', 'Action', 'Horror', 'Comedy', 'Romance', 'Comedy', 'Music', 'Romance', 'Drama', 'Thriller', 'Action', 'War', 'Drama', 'History', 'Crime', 'Family', 'Fantasy', 'Crime', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Thriller', 'Mystery', 'Drama', 'Romance', 'Comedy', 'Drama', 'Drama', 'Comedy', 'Family', 'Comedy', 'Animation', 'Adventure', 'Crime', 'Drama', 'Mystery', 'Animation', 'Adventure', 'Family', 'Comedy', 'Science Fiction', 'Action', 'Drama', 'Thriller', 'Fantasy', 'Mystery', 'Thriller', 'Crime', 'Drama', 'Romance', 'Thriller', 'Action', 'Thriller', 'Adventure', 'Fantasy', 'Drama', 'Comedy', 'Science Fiction', 'Family', 'Western', 'Drama', 'Adventure', 'Thriller', 'Drama', 'Action', 'Thriller', 'Crime', 'Action', 'Comedy', 'Romance', 'Comedy', 'Family', 'Fantasy', 'Comedy', 'Action', 'Thriller', 'Crime', 'Drama', 'Drama', 'Romance', 'Animation', 'Comedy', 'Romance', 'Adventure', 'Drama', 'Action', 'History', 'Comedy', 'Drama', 'Romance', 'War', 'Action', 'Drama', 'Action', 'Drama', 'Drama', 'Thriller', 'Crime', 'Mystery', 'Drama', 'Fantasy', 'Drama', 'Drama', 'History', 'Comedy', 'Drama', 'Mystery', 'Thriller', 'Crime', 'Comedy', 'Romance', 'War', 'Drama', 'Action', 'Action', 'Drama', 'Thriller', 'Comedy', 'Romance', 'Drama', 'Romance', 'Fantasy', 'Drama', 'Comedy', 'Family', 'Adventure', 'Adventure', 'Animation', 'Fantasy', 'Documentary', 'Drama', 'Action', 'Adventure', 'Action', 'Thriller', 'Comedy', 'Action', 'Comedy', 'Action', 'Crime', 'Documentary', 'Action', 'Adventure', 'Comedy', 'Drama', 'Mystery', 'Family', 'Animation', 'Drama', 'Action', 'War', 'Science Fiction', 'Fantasy', 'Drama', 'Family', 'Documentary', 'Adventure', 'Action', 'Comedy', 'Crime', 'Drama', 'War', 'Drama', 'Romance', 'Drama', 'Thriller', 'Science Fiction', 'Drama', 'Thriller', 'Drama', 'Family', 'Adventure', 'Comedy', 'Fantasy', 'Drama', 'Comedy', 'Romance', 'Thriller', 'Horror', 'Comedy', 'Drama', 'Drama', 'Comedy', 'Romance', 'Foreign', 'Action', 'Drama', 'Thriller', 'War', 'Comedy', 'Thriller', 'Drama', 'Horror', 'Science Fiction', 'Science Fiction', 'Animation', 'Family', 'Drama', 'Thriller', 'Crime', 'Animation', 'Family', 'Adventure', 'Drama', 'Music', 'Drama', 'Thriller', 'Action', 'Adventure', 'Drama', 'Family', 'Crime', 'Drama', 'Thriller', 'Drama', 'Romance', 'Drama', 'Family', 'Comedy', 'Drama', 'Drama', 'Romance', 'Action', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Comedy', 'Adventure', 'Drama', 'History', 'Drama', 'Family', 'Comedy', 'Comedy', 'Comedy', 'Drama', 'Comedy', 'Documentary', 'Drama', 'Horror', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Drama', 'History', 'Romance', 'War', 'Comedy', 'Crime', 'Horror', 'Thriller', 'Romance', 'Comedy', 'Drama', 'History', 'Drama', 'Action', 'Action', 'Horror', 'Thriller', 'Science Fiction', 'Horror', 'Thriller', 'Mystery', 'Animation', 'Comedy', 'Fantasy', 'Thriller', 'Adventure', 'Comedy', 'Science Fiction', 'Drama', 'Horror', 'Action', 'Thriller', 'Science Fiction', 'Drama', 'History', 'Romance', 'Comedy', 'Romance', 'Comedy', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Adventure', 'Horror', 'Thriller', 'Crime', 'Drama', 'Comedy', 'Foreign', 'Fantasy', 'Comedy', 'Romance', 'Horror', 'Thriller', 'Action', 'Comedy', 'Crime', 'Thriller', 'Mystery', 'Comedy', 'Drama', 'Drama', 'Fantasy', 'Comedy', 'Family', 'Comedy', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Mystery', 'Thriller', 'Comedy', 'Science Fiction', 'Thriller', 'Crime', 'Drama', 'Mystery', 'Action', 'Comedy', 'Crime', 'Romance', 'Adventure', 'Comedy', 'Drama', 'Science Fiction', 'Family', 'Adventure', 'Drama', 'Drama', 'History', 'Adventure', 'Action', 'Comedy', 'Comedy', 'Romance', 'Drama', 'Action', 'War', 'Drama', 'Thriller', 'Documentary', 'Mystery', 'Thriller', 'Drama', 'Romance', 'Comedy', 'Drama', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Fantasy', 'Drama', 'Comedy', 'Family', 'Action', 'Thriller', 'Thriller', 'Science Fiction', 'Adventure', 'Action', 'Comedy', 'Romance', 'Drama', 'Crime', 'Thriller', 'Music', 'Romance', 'Drama', 'Horror', 'Thriller', 'War', 'Comedy', 'Drama', 'Romance', 'Horror', 'Drama', 'Mystery', 'Drama', 'Romance', 'Comedy', 'Family', 'Thriller', 'Action', 'Crime', 'History', 'Drama', 'Comedy', 'Family', 'Drama', 'Science Fiction', 'Mystery', 'Comedy', 'Drama', 'Family', 'Comedy', 'Family', 'Science Fiction', 'Crime', 'Drama', 'Thriller', 'Drama', 'Comedy', 'Drama', 'Adventure', 'Drama', 'Action', 'Romance', 'Family', 'Comedy', 'Drama', 'Crime', 'Thriller', 'Action', 'Comedy', 'Drama', 'History', 'Family', 'Animation', 'Horror', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Action', 'Adventure', 'Drama', 'Thriller', 'Fantasy', 'Drama', 'Comedy', 'Science Fiction', 'Romance', 'Western', 'Action', 'Adventure', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Romance', 'Drama', 'Comedy', 'Romance', 'Crime', 'Drama', 'History', 'Drama', 'Romance', 'Adventure', 'Animation', 'Comedy', 'Drama', 'Fantasy', 'Horror', 'Thriller', 'Drama', 'Horror', 'Science Fiction', 'Animation', 'Comedy', 'Drama', 'Action', 'Adventure', 'Drama', 'History', 'Crime', 'Drama', 'Thriller', 'Drama', 'Romance', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Action', 'Thriller', 'Horror', 'Mystery', 'Science Fiction', 'Action', 'Adventure', 'Thriller', 'Documentary', 'Animation', 'Comedy', 'Family', 'War', 'Drama', 'Comedy', 'Drama', 'Romance', 'Action', 'Drama', 'Thriller', 'Mystery', 'Crime', 'Drama', 'Western', 'Action', 'Drama', 'War', 'Comedy', 'Drama', 'Thriller', 'Crime', 'Action', 'Mystery', 'Drama', 'Thriller', 'Horror', 'Crime', 'Drama', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Comedy', 'Drama', 'Romance', 'Thriller', 'Science Fiction', 'Action', 'Crime', 'Drama', 'Music', 'Romance', 'Horror', 'Mystery', 'Thriller', 'Romance', 'Drama', 'Drama', 'Romance', 'Action', 'Adventure', 'Fantasy', 'Drama', 'Action', 'Crime', 'Drama', 'Documentary', 'Music', 'Drama', 'Drama', 'History', 'Action', 'Drama', 'Thriller', 'Adventure', 'Action', 'Thriller', 'Crime', 'Adventure', 'Comedy', 'Romance', 'Comedy', 'Romance', 'Romance', 'Comedy', 'Crime', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Romance', 'Drama', 'Documentary', 'Music', 'Family', 'Adventure', 'Action', 'Science Fiction', 'Adventure', 'Thriller', 'Drama', 'Romance', 'Drama', 'War', 'Comedy', 'Action', 'Adventure', 'Thriller', 'Adventure', 'Action', 'Comedy', 'Documentary', 'Adventure', 'Family', 'Fantasy', 'Comedy', 'Drama', 'Horror', 'Mystery', 'Thriller', 'Adventure', 'Fantasy', 'Action', 'Comedy', 'Drama', 'Music', 'Romance', 'Action', 'Adventure', 'Drama', 'Drama', 'Comedy', 'Thriller', 'Comedy', 'Fantasy', 'Horror', 'Horror', 'Thriller', 'Documentary', 'Thriller', 'Drama', 'Crime', 'Action', 'Science Fiction', 'Horror', 'Thriller', 'Comedy', 'Crime', 'Romance', 'Drama', 'Animation', 'Science Fiction', 'Action', 'Adventure', 'Crime', 'Drama', 'Thriller', 'Adventure', 'Drama', 'Comedy', 'Comedy', 'Drama', 'History', 'Adventure', 'Family', 'Drama', 'Drama', 'Comedy', 'Romance', 'Drama', 'Drama', 'Comedy', 'Romance', 'Action', 'Adventure', 'Drama', 'History', 'Western', 'Action', 'Comedy', 'Crime', 'Drama', 'Thriller', 'Science Fiction', 'Thriller', 'Horror', 'Thriller', 'Science Fiction', 'Horror', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Comedy', 'Comedy', 'Drama', 'History', 'Action', 'Science Fiction', 'Crime', 'Adventure', 'Animation', 'Comedy', 'Family', 'Drama', 'Action', 'Western', 'Drama', 'Comedy', 'Horror', 'Music', 'Drama', 'Comedy', 'Drama', 'Music', 'Horror', 'Action', 'Thriller', 'Crime', 'Comedy', 'Drama', 'Drama', 'Music', 'Action', 'Horror', 'Science Fiction', 'Horror', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Drama', 'Comedy', 'Drama', 'Romance', 'Romance', 'Drama', 'Comedy', 'Romance', 'Comedy', 'Horror', 'Comedy', 'Fantasy', 'Comedy', 'Drama', 'Drama', 'Thriller', 'Drama', 'Action', 'Romance', 'War', 'Drama', 'Thriller', 'Adventure', 'Drama', 'Romance', 'Action', 'Comedy', 'Romance', 'Drama', 'Drama', 'Action', 'Crime', 'Thriller', 'Drama', 'History', 'War', 'Thriller', 'War', 'Adventure', 'Documentary', 'Drama', 'Fantasy', 'Animation', 'Romance', 'Family', 'Horror', 'Comedy', 'Action', 'Fantasy', 'Science Fiction', 'Thriller', 'Drama', 'Romance', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Action', 'Adventure', 'Drama', 'War', 'Drama', 'Foreign', 'Drama', 'Family', 'Comedy', 'Comedy', 'Fantasy', 'Drama', 'Mystery', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'War', 'Drama', 'History', 'Adventure', 'Fantasy', 'Action', 'Comedy', 'Family', 'Action', 'Comedy', 'Action', 'Adventure', 'Drama', 'History', 'Music', 'Drama', 'Action', 'Drama', 'Thriller', 'Drama', 'Drama', 'Romance', 'Comedy', 'Drama', 'Romance', 'Adventure', 'Comedy', 'Crime', 'Mystery', 'Romance', 'Thriller', 'Thriller', 'Action', 'Crime', 'Drama', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Adventure', 'Adventure', 'Action', 'Comedy', 'Music', 'Drama', 'Romance', 'Adventure', 'Comedy', 'Drama', 'Romance', 'Drama', 'Romance', 'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Comedy', 'Romance', 'Comedy', 'Romance', 'Drama', 'Drama', 'Thriller', 'Crime', 'Drama', 'Thriller', 'Science Fiction', 'Drama', 'Comedy', 'Music', 'Adventure', 'Animation', 'Comedy', 'Family', 'Drama', 'Romance', 'Action', 'Crime', 'Drama', 'Romance', 'Thriller', 'Western', 'Comedy', 'Drama', 'Crime', 'Horror', 'Mystery', 'Thriller', 'Science Fiction', 'Thriller', 'Romance', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Fantasy', 'Drama', 'Action', 'Comedy', 'Science Fiction', 'Action', 'Thriller', 'Fantasy', 'Comedy', 'Romance', 'Drama', 'Horror', 'Thriller', 'Family', 'Action', 'Comedy', 'Drama', 'Adventure', 'Fantasy', 'Drama', 'Music', 'Thriller', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Music', 'Romance', 'Comedy', 'Drama', 'Crime', 'Action', 'Thriller', 'Action', 'Animation', 'Action', 'Family', 'Action', 'Adventure', 'Crime', 'Drama', 'Comedy', 'Drama', 'Romance', 'Crime', 'Drama', 'Mystery', 'Romance', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Fantasy', 'Drama', 'Crime', 'Action', 'Adventure', 'Comedy', 'Family', 'Family', 'Fantasy', 'Romance', 'Crime', 'Drama', 'Western', 'Comedy', 'Crime', 'Drama', 'Comedy', 'Horror', 'Drama', 'Science Fiction', 'Adventure', 'Action', 'Comedy', 'Drama', 'Romance', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance', 'Thriller', 'Comedy', 'Romance', 'Thriller', 'Crime', 'Drama', 'Mystery', 'Horror', 'Thriller', 'Romance', 'Romance', 'Thriller', 'Comedy', 'Romance', 'Comedy', 'Crime', 'Drama', 'War', 'Action', 'Comedy', 'Horror', 'Comedy', 'Music', 'Horror', 'Thriller', 'Comedy', 'Romance', 'Documentary', 'Drama', 'Thriller', 'History', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Comedy', 'Drama', 'Action', 'Adventure', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Drama', 'Romance', 'Adventure', 'Drama', 'Family', 'Action', 'History', 'War', 'Drama', 'Music', 'Romance', 'Drama', 'Thriller', 'Music', 'Comedy', 'Drama', 'Fantasy', 'Animation', 'Science Fiction', 'Family', 'Thriller', 'Horror', 'Action', 'Crime', 'Drama', 'Drama', 'Horror', 'Fantasy', 'Comedy', 'Drama', 'Action', 'Comedy', 'Thriller', 'Crime', 'Adventure', 'Fantasy', 'Drama', 'Romance', 'Action', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Drama', 'Adventure', 'Comedy', 'Crime', 'Mystery', 'Romance', 'Animation', 'Adventure', 'Comedy', 'Family', 'Drama', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'Comedy', 'Action', 'Drama', 'Thriller', 'Animation', 'Adventure', 'Family', 'Comedy', 'Adventure', 'Comedy', 'Family', 'Science Fiction', 'Drama', 'History', 'Romance', 'Drama', 'Drama', 'Thriller', 'Action', 'Thriller', 'Crime', 'Action', 'Thriller', 'Family', 'Science Fiction', 'Comedy', 'Crime', 'Drama', 'Comedy', 'Thriller', 'Action', 'Comedy', 'Crime', 'Drama', 'Drama', 'Action', 'Thriller', 'Horror', 'Science Fiction', 'Drama', 'Music', 'Romance', 'Fantasy', 'Family', 'R

In [45]:
unique_genres_list = set(genres_list)
print(f"unique genres of movies in the dataset are : {unique_genres_list}\ntotal number of unique genres is {len(unique_genres_list)}")

unique genres of movies in the dataset are : {'Documentary', 'Drama', 'Mystery', 'Adventure', 'Crime', 'Science Fiction', 'TV Movie', 'Comedy', 'War', 'Foreign', 'Action', 'Fantasy', 'Thriller', 'Music', 'History', 'Romance', 'Western', 'Animation', 'Horror', 'Family'}
total number of unique genres is 20

# 4 . Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI?

In [46]:
df.columns

Index(['budget', 'genres', 'imdb_id', 'original_language', 'original_title',
       'revenue', 'cast', 'crew', 'profit', 'roi'],
      dtype='object')

In [47]:
no_na_crew_df = df[df['crew'].notnull()]
len(no_na_crew_df)

2984

In [48]:
def prod_dir(row) :
  try :
    producers_list = []
    directors_list = []
    for elem in row['crew'] :
      if elem['job'] == 'Producer' :
        producers_list.append(elem['name']) 
      if elem['job'] == 'Director' :
        directors_list.append(elem['name'])
     
    row['producers'] = producers_list
    row['directors'] = directors_list
    return row

  except :
    return []

In [49]:
df.head(2)

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit,roi
0,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en,Hot Tub Time Machine 2,12314651,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",-1685349,-12.038207
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en,The Princess Diaries 2: Royal Engagement,95149435,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",55149435,137.873588

In [50]:
prod_dir(no_na_crew_df.iloc[1])

budget                                                        40000000
genres               [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
imdb_id                                                      tt0368933
original_language                                                   en
original_title                The Princess Diaries 2: Royal Engagement
revenue                                                       95149435
cast                 [{'cast_id': 1, 'character': 'Mia Thermopolis'...
crew                 [{'credit_id': '52fe43fe9251416c7502563d', 'de...
profit                                                        55149435
roi                                                         137.873588
producers            [Whitney Houston, Mario Iscovich, Debra Martin...
directors                                             [Garry Marshall]
Name: 1, dtype: object

In [51]:
df1 = no_na_crew_df.apply(prod_dir, axis = 1)

In [52]:
df1.shape

(2984, 12)

In [53]:
df1[['original_title','producers','directors']].set_index('original_title')

,producers,directors
original_title,,
Hot Tub Time Machine 2,[Andrew Panay],[Steve Pink]
The Princess Diaries 2: Royal Engagement,"[Whitney Houston, Mario Iscovich, Debra Martin...",[Garry Marshall]
Whiplash,"[David Lancaster, Michel Litvak, Jason Blum, H...",[Damien Chazelle]
Kahaani,[Sujoy Ghosh],[Sujoy Ghosh]
마린보이,[],[Jong-seok Yoon]
...,...,...
Chasers,[James G. Robinson],[Dennis Hopper]
Vi är bäst!,[Lars J√∂nsson],[Lukas Moodysson]
The Long Kiss Goodnight,"[Stephanie Austin, Shane Black, Renny Harlin, ...",[Renny Harlin]
Along Came Polly,"[Danny DeVito, Michael Shamberg, Stacey Sher]",[John Hamburg]
Abduction,"[Doug Davison, Roy Lee, Ellen Goldsmith-Vein, ...",[John Singleton]

In [54]:
type(df1['producers'])

pandas.core.series.Series

In [55]:
producer_dict = {}
# iterating over each row of df 
for index, row in df1.iterrows():
# iterarting over producer column of each row
  for prod in row['producers'] :
#updating producer dictionary for each producer based on his roi of his movies
    if prod not in producer_dict.keys() :
      producer_dict[prod] = [row['roi']]
    else :
      value_of_prod_key = producer_dict[prod]
      value_of_prod_key.append(row['roi'])
      producer_dict[prod] = value_of_prod_key

In [56]:
top_3_producers = pd.DataFrame.from_dict(producer_dict, orient = 'index').mean(axis = 1).reset_index().rename({'index':'PRODUCER', 0:'avg(ROI)'},  axis = 1).sort_values(by = 'avg(ROI)',ascending = False).iloc[0:3]

In [57]:
top_3_producers

         PRODUCER      avg(ROI)
1860   Amir Zbeda  1.288939e+06
2323  Robin Cowie  4.132333e+05
2324   Gregg Hale  4.132333e+05

# 5. Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor.

In [58]:
no_na_cast_df = df[df['cast'].notnull()]

In [59]:
actor_movie_dict = {}
for index , row in  no_na_cast_df.iterrows() :
  #print(row)
  for elem in row['cast'] :
    if elem['name'] not in actor_movie_dict.keys() :
      actor_movie_dict[elem['name']] = [row['imdb_id']]
    else :
      value_of_actor_key = actor_movie_dict[elem['name']]
      value_of_actor_key.append((row['imdb_id']))
      actor_movie_dict[elem['name']] = value_of_actor_key

In [60]:
actor_movies_num = pd.DataFrame.from_dict(actor_movie_dict , orient = 'index').count(axis = 1).reset_index().rename(columns = {'index':'Actor',0 :'number of movies'}).sort_values(by = 'number of movies', ascending = False)

In [61]:
top_actors = actor_movies_num.loc[actor_movies_num['number of movies'] == actor_movies_num['number of movies'].max(),['Actor','number of movies']]
top_actors

                  Actor  number of movies
7008     Robert De Niro                30
594   Samuel L. Jackson                30

In [62]:
df_dict = {'actor': [] , 'movies' : [], 'profits' : [], 'roi' : [], 'genres' : []}
for i, r in no_na_cast_df.iterrows() :
  for e in r['cast'] :
    if e['name'] in list(top_actors['Actor']) :
      df_dict['actor'].append(e['name'])
      df_dict['movies'].append(r['original_title'])
      df_dict['profits'].append(r['profit'])
      df_dict['roi'].append(r['roi'])
      genres_set = set()
      for f in r['genres'] :
        genres_set.add(f['name'])
      df_dict['genres'].append(genres_set)

In [63]:
top_actors_info = pd.DataFrame(df_dict)

In [64]:
top_actors_info

,actor,movies,profits,roi,genres
0,Samuel L. Jackson,Changing Lanes,49935764,110.968364,"{Thriller, Action, Adventure, Crime}"
1,Samuel L. Jackson,The Hateful Eight,111760117,254.000266,"{Crime, Western, Drama, Mystery}"
2,Robert De Niro,This Boy’s Life,-12345038,-75.045824,{Drama}
3,Robert De Niro,What Just Happened,-18326578,-73.306312,"{Drama, Comedy}"
4,Robert De Niro,Mad Dog and Glory,-5368414,-32.634736,"{Romance, Crime, Drama, Comedy}"
5,Samuel L. Jackson,Coming to America,249752301,640.390515,"{Romance, Comedy}"
6,Samuel L. Jackson,Star Wars: Episode III - Revenge of the Sith,737000000,652.212389,"{Action, Adventure, Science Fiction}"
7,Robert De Niro,The Good Shepherd,-25091435,-29.519335,"{History, Thriller, Drama}"
8,Robert De Niro,Lenny Bruce: Swear to Tell the Truth,-16428650,-99.870213,"{Documentary, Comedy}"
9,Robert De Niro,Red Lights,-448826,-3.205900,{Thriller}
10,Samuel L. Jackson,Meeting Evil,0,0.000000,"{Thriller, Crime, Drama, Mystery}"
11,Samuel L. Jackson,The Avengers,1299557910,590.708141,"{Action, Adventure, Science Fiction}"
12,Robert De Niro,Falling in Love,-5320943,-32.346158,"{Romance, Drama}"
13,Samuel L. Jackson,Jumper,137231186,161.448454,"{Fantasy, Adventure, Science Fiction}"
14,Robert De Niro,Wag the Dog,49256513,328.376753,"{Drama, Comedy}"
15,Robert De Niro,Meet the Parents,275444045,500.807355,"{Romance, Comedy}"
16,Robert De Niro,Marvin's Room,-10196695,-44.333457,{Drama}
17,Robert De Niro,Sleepers,121615285,276.398375,"{Thriller, Crime, Drama}"
18,Robert De Niro,The Fan,-36373581,-66.133784,"{Thriller, Drama, Mystery}"
19,Robert De Niro,The Family,6894225,22.980750,"{Crime, Action, Comedy}"
20,Samuel L. Jackson,Shaft,61196498,133.035865,"{Thriller, Action, Adventure, Crime}"
21,Samuel L. Jackson,Snakes on a Plane,29022014,87.945497,"{Horror, Thriller, Action, Crime}"
22,Robert De Niro,Stone,-12520282,-56.910373,{Drama}
23,Samuel L. Jackson,The Man,-4067638,-24.727283,"{Action, Crime, Comedy}"
24,Robert De Niro,Being Flynn,-15909848,-96.716401,{Drama}
25,Samuel L. Jackson,RoboCop,122688965,102.240804,"{Action, Science Fiction}"
26,Samuel L. Jackson,Jurassic Park,857100000,1360.476190,"{Adventure, Science Fiction}"
27,Samuel L. Jackson,Cell,-15316969,-93.112274,"{Thriller, Science Fiction, Horror}"
28,Samuel L. Jackson,Star Wars: Episode II - Attack of the Clones,529398328,441.165273,"{Action, Adventure, Science Fiction}"
29,Robert De Niro,Righteous Kill,13174566,21.957610,"{Thriller, Drama, Action, Crime}"
30,Samuel L. Jackson,Eddie Murphy Raw,34054655,207.019179,{Comedy}
31,Samuel L. Jackson,Captain America: The Winter Soldier,544766572,320.450925,"{Action, Adventure, Science Fiction}"
32,Robert De Niro,American Hustle,211171807,527.929517,"{Crime, Drama}"
33,Samuel L. Jackson,Jackie Brown,27673162,230.609683,"{Romance, Crime, Comedy}"
34,Robert De Niro,Jackie Brown,27673162,230.609683,"{Romance, Crime, Comedy}"
35,Samuel L. Jackson,African Cats,-1209544,-7.352851,"{Documentary, Family, Adventure}"
36,Samuel L. Jackson,Big Game,-1000000,-11.764706,"{Thriller, Action, Adventure}"
37,Robert De Niro,Raging Bull,5000000,27.777778,{Drama}
38,Robert De Niro,Angel Heart,185632,1.091953,"{Thriller, Horror, Mystery}"
39,Robert De Niro,Joy,41134059,68.556765,"{Drama, Comedy}"
40,Samuel L. Jackson,Black Snake Moan,-4096154,-27.307693,{Drama}
41,Robert De Niro,The Deer Hunter,35000000,233.333333,"{War, Drama}"
42,Robert De Niro,Stanley & Iris,-17179985,-74.695587,"{Romance, Drama}"
43,Samuel L. Jackson,Sea of Love,91879513,483.576384,"{Crime, Drama, Mystery}"
44,Robert De Niro,Machete,11327899,56.639495,"{Thriller, Action, Comedy}"
45,Robert De Niro,Mean Streets,2500000,500.000000,"{Crime, Drama}"
46,Robert De Niro,Men of Honor,16814909,52.546591,{Drama}
47,Samuel L. Jackson,Deep Blue Sea,13648228,22.747047,"{Thriller, Action, Science Fiction}"
48,Samuel L. Jackson,Basic,-7207439,-14.414878,"{Thriller, Crime, Action, Drama, Mystery}"
49,Robert De Niro,Analyze This,96885658,121.107072,"{Crime, Comedy}"
50,Samuel L. Jackson,The Incredibles,539442092,586.350100,"{Family, Action, Adventure, Animation}"
51,Samuel L. Jackson,Avengers: Age of Ultron,1125403694,401.929891,"{Action, Adventure, Science Fiction}"
52,Samuel L. Jackson,Out of Sight,29745568,61.969933,"{Romance, Crime, Comedy}"
53,Robert De Niro,The Bag Man,-16393426,-99.656085,"{Thriller, Crime, Drama}"
54,Robert De Niro,The Score,3069884,4.514535,"{Thriller, Action, Crime}"
55,Samuel L. Jackson,Patriot Games,133051587,295.670193,"{Crime, Thriller, Action, Drama}"
56,Robert De Niro,Backdraft,77368585,103.158113,"{Thriller, Crime, Action, Drama, Mystery}"
57,Samuel L. Jackson,S.W.A.T.,36643346,45.804183,"{Thriller, Action, Crime}"
58,Samuel L. Jackson,Freedomland,-23009372,-61.089531,"{Thriller, Crime, Drama, Mystery}"
59,Samuel L. Jackson,The Long Kiss Goodnight,24456761,37.625786,"{Thriller, Crime, Mystery, Action}"

# 6. Top 3 directors prefer which actors the most?

In [65]:
df.head(2)

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit,roi
0,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en,Hot Tub Time Machine 2,12314651,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",-1685349,-12.038207
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en,The Princess Diaries 2: Royal Engagement,95149435,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",55149435,137.873588

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             3000 non-null   int64
 1   genres             2993 non-null   object
 2   imdb_id            3000 non-null   object
 3   original_language  3000 non-null   object
 4   original_title     3000 non-null   object
 5   revenue            3000 non-null   int64
 6   cast               2987 non-null   object
 7   crew               2984 non-null   object
 8   profit             3000 non-null   int64
 9   roi                3000 non-null   float64
dtypes: float64(1), int64(3), object(6)
memory usage: 234.5+ KB

In [67]:
no_na_crew_df = df[df['crew'].notnull()]
no_na_crew_df.head()

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit,roi
0,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en,Hot Tub Time Machine 2,12314651,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",-1685349,-12.038207
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en,The Princess Diaries 2: Royal Engagement,95149435,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",55149435,137.873588
2,3300000,"[{'id': 18, 'name': 'Drama'}]",tt2582802,en,Whiplash,13092000,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",9792000,296.727273
3,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",tt1821480,hi,Kahaani,16000000,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",14800000,1233.333333
4,16450000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",tt1380152,ko,마린보이,3923970,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",-12526030,-76.146079

In [68]:
def dir(row) :
  try :
    directors_list = []
    for elem in   row['crew'] :
      if elem['job'] == 'Director' :
        directors_list.append(elem['name'])
    row['directors'] = directors_list
    return row

  except :
    return []

In [69]:
dir(no_na_crew_df.iloc[0])

budget                                                        14000000
genres                                  [{'id': 35, 'name': 'Comedy'}]
imdb_id                                                      tt2637294
original_language                                                   en
original_title                                  Hot Tub Time Machine 2
revenue                                                       12314651
cast                 [{'cast_id': 4, 'character': 'Lou', 'credit_id...
crew                 [{'credit_id': '59ac067c92514107af02c8c8', 'de...
profit                                                        -1685349
roi                                                         -12.038207
directors                                                 [Steve Pink]
Name: 0, dtype: object

In [70]:
no_na_crew_df = no_na_crew_df.apply(dir , axis = 1)

In [71]:
dir_info = {}
for i, r in no_na_crew_df.iterrows() :
  for d in r['directors'] :
    if d not in dir_info.keys() :
      dir_info[d] = [r['roi']]
    else :
      v = dir_info[d]
      v.append(r['roi'])
      dir_info[d] = v

In [72]:
df['roi'].mean()

893.6222915317032

In [73]:
directors_roi = pd.DataFrame.from_dict(dir_info, orient = 'index').mean(axis = 1).reset_index()

In [74]:
sorted_drcts_roi = directors_roi.rename(columns = {'index':'name of directors',0:'avg roi'}).sort_values(by = 'avg roi',ascending = False)

In [75]:
top_3_directors = sorted_drcts_roi.iloc[0:3]
top_3_directors

     name of directors       avg roi
1077         Oren Peli  1.288939e+06
1364     Daniel Myrick  4.132333e+05
1861    Park Hoon-Jung  2.215690e+05

In [76]:
no_na_cast_crew_df = no_na_crew_df[no_na_crew_df['cast'].notnull()]
no_na_cast_crew_df['cast'][0]

[{'cast_id': 4,
  'character': 'Lou',
  'credit_id': '52fe4ee7c3a36847f82afae7',
  'gender': 2,
  'id': 52997,
  'name': 'Rob Corddry',
  'order': 0,
  'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'},
 {'cast_id': 5,
  'character': 'Nick',
  'credit_id': '52fe4ee7c3a36847f82afaeb',
  'gender': 2,
  'id': 64342,
  'name': 'Craig Robinson',
  'order': 1,
  'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'},
 {'cast_id': 6,
  'character': 'Jacob',
  'credit_id': '52fe4ee7c3a36847f82afaef',
  'gender': 2,
  'id': 54729,
  'name': 'Clark Duke',
  'order': 2,
  'profile_path': '/oNzK0umwm5Wn0wyEbOy6TVJCSBn.jpg'},
 {'cast_id': 7,
  'character': 'Adam Jr.',
  'credit_id': '52fe4ee7c3a36847f82afaf3',
  'gender': 2,
  'id': 36801,
  'name': 'Adam Scott',
  'order': 3,
  'profile_path': '/5gb65xz8bzd42yjMAl4zwo4cvKw.jpg'},
 {'cast_id': 8,
  'character': 'Hot Tub Repairman',
  'credit_id': '52fe4ee7c3a36847f82afaf7',
  'gender': 2,
  'id': 54812,
  'name': 'Chevy Chase',
  'order': 4,
  'profile_path': '/svjpyYtPwtjvRxX9IZnOmOkhDOt.jpg'},
 {'cast_id': 9,
  'character': 'Jill',
  'credit_id': '52fe4ee7c3a36847f82afafb',
  'gender': 1,
  'id': 94098,
  'name': 'Gillian Jacobs',
  'order': 5,
  'profile_path': '/rBnhe5vhNPnhRUdtYahBWx90fJM.jpg'},
 {'cast_id': 10,
  'character': 'Sophie',
  'credit_id': '52fe4ee7c3a36847f82afaff',
  'gender': 1,
  'id': 1159009,
  'name': 'Bianca Haase',
  'order': 6,
  'profile_path': '/4x3nbtD8q8phAJPmoGWXPvz0iM.jpg'},
 {'cast_id': 11,
  'character': 'Kelly',
  'credit_id': '5524ec51c3a3687df3000dbb',
  'gender': 1,
  'id': 86624,
  'name': 'Collette Wolfe',
  'order': 7,
  'profile_path': '/aSD4h5379b2eEw3bLou9ByLimmq.jpg'},
 {'cast_id': 13,
  'character': 'Brad',
  'credit_id': '5524ec8ec3a3687ded000d72',
  'gender': 2,
  'id': 466505,
  'name': 'Kumail Nanjiani',
  'order': 9,
  'profile_path': '/x4nAztHY72SVciRfxEsbhIVTsIu.jpg'},
 {'cast_id': 14,
  'character': 'Courtney',
  'credit_id': '5524ec9bc3a3687df8000d13',
  'gender': 1,
  'id': 70776,
  'name': 'Kellee Stewart',
  'order': 10,
  'profile_path': '/w3xmsEPmJc1Cf0dQ4aIn8YmlHbk.jpg'},
 {'cast_id': 15,
  'character': 'Terry',
  'credit_id': '5524eca892514171cb008237',
  'gender': 2,
  'id': 347335,
  'name': 'Josh Heald',
  'order': 11,
  'profile_path': '/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg'},
 {'cast_id': 16,
  'character': 'Susan',
  'credit_id': '5524ecb7925141720c001116',
  'gender': 0,
  'id': 1451392,
  'name': 'Gretchen Koerner',
  'order': 12,
  'profile_path': '/muULPexCTJGyJba4yKzxronpD50.jpg'},
 {'cast_id': 17,
  'character': 'Herself',
  'credit_id': '5524ecc3c3a3687ded000d74',
  'gender': 1,
  'id': 98879,
  'name': 'Lisa Loeb',
  'order': 13,
  'profile_path': '/bGqg58ca0bZR38z9HliUMmeNGE.jpg'},
 {'cast_id': 18,
  'character': 'Herself',
  'credit_id': '5524ecd3c3a3687e11000ed3',
  'gender': 1,
  'id': 1394648,
  'name': 'Jessica Williams',
  'order': 14,
  'profile_path': '/A4syKjkcYB92wLEhH0c0hC3BCpz.jpg'},
 {'cast_id': 19,
  'character': 'Himself',
  'credit_id': '5524ece6925141718d001009',
  'gender': 0,
  'id': 1451393,
  'name': 'Bruce Buffer',
  'order': 15,
  'profile_path': None},
 {'cast_id': 20,
  'character': 'Shot Girl',
  'credit_id': '5524ecf5c3a3687e08000dc2',
  'gender': 0,
  'id': 1451394,
  'name': 'Mariana Paola Vicente',
  'order': 16,
  'profile_path': '/ckPllza8624UHWGHCbLShkLxCD1.jpg'},
 {'cast_id': 33,
  'character': 'Choozy Doozy Host',
  'credit_id': '555844da9251412afe0013a9',
  'gender': 2,
  'id': 2224,
  'name': 'Christian Slater',
  'order': 17,
  'profile_path': '/3ElLWjnvchMS6Q4cIQOK8QNAoMG.jpg'},
 {'cast_id': 35,
  'character': 'Gary Winkle',
  'credit_id': '55872027c3a3683853005074',
  'gender': 0,
  'id': 185805,
  'name': 'Jason Jones',
  'order': 18,
  'profile_path': '/aIoCw6vo8AGMdsQRAI5g2t0yJT3.jpg'},
 {'cast_id': 36,
  'character': 'Bridesmaid',
  'credit_id': '55efe971c3a368090c00cd1b',
  'gender': 0,
  'id': 1507448,
  'name': 'Olivia Jordan',
  'order': 19,
  'profile_path': '/szMukAEiIDeasel0lvyaeyKuych.jpg'},
 {'cast_id': 37,
  'character': 'Christine',
  'credit_id': '55efe980c3a36871bf008176',
  'gender': 1,
  'id': 1334091,
  'name': 'Christine Bently',
  'order': 20,
  'profile_path': '/oUZltnGa55OXE52hfyPTfCshuNy.jpg'},
 {'cast_id': 38,
  'character': 'Excited Girl',
  'credit_id': '55efe98e9251413e3201d316',
  'gender': 0,
  'id': 557803,
  'name': 'Stacey Asaro',
  'order': 21,
  'profile_path': '/qTPdlr1dXf3kNdyHuDsgtGC0HCC.jpg'},
 {'cast_id': 64,
  'character': 'Adam (uncredited)',
  'credit_id': '58f2135ac3a3682e95008b91',
  'gender': 2,
  'id': 3036,
  'name': 'John Cusack',
  'order': 22,
  'profile_path': '/uKydQYuZ9TnCzvbQLtj6j98vWAT.jpg'},
 {'cast_id': 65,
  'character': 'J-Bird',
  'credit_id': '59ac0240c3a3682cc802c399',
  'gender': 2,
  'id': 59256,
  'name': 'Adam Herschman',
  'order': 23,
  'profile_path': '/wZMwiuX1DslF6hDS50z9OTN6z1X.jpg'},
 {'cast_id': 66,
  'character': 'Bridesmaid',
  'credit_id': '59ac02cd925141079d02b1b4',
  'gender': 1,
  'id': 129714,
  'name': 'Kisha Sierra',
  'order': 24,
  'profile_path': None}]

In [77]:
 for d in top_3_directors['name of directors'] :
   print(d)

Oren Peli
Daniel Myrick
Park Hoon-Jung

In [78]:
dir_act_dict = {}
for d in top_3_directors['name of directors'] :
  for i, r in no_na_cast_crew_df.iterrows() :
    for c in r['cast'] :
      if (d in r['directors']) and (d not in dir_act_dict.keys()) :
        dir_act_dict[d] = [c['name']]
      elif  d in r['directors'] :
         z = dir_act_dict[d]
         z.append(c['name'])
         dir_act_dict[d] = z
      else :
        pass

In [79]:
dir_act_dict

{'Oren Peli': ['Katie Featherston',
  'Micah Sloat',
  'Mark Fredrichs',
  'Amber Armstrong',
  'Ashley Palmer'],
 'Daniel Myrick': ['Michael C. Williams',
  'Heather Donahue',
  'Joshua Leonard',
  'Bob Griffith',
  'Jim King',
  'Sandra S√°nchez',
  'Ed Swanson',
  'Patricia DeCou',
  'Mark Mason',
  'Jackie Hallex'],
 'Park Hoon-Jung': ['Choi Min-sik',
  'Jeong Man-sik',
  'Kim Sang-ho',
  'Sung Yu-bin',
  'Jung Suk-won',
  'Lee Eun-woo']}